In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
metadata = pd.read_csv("/dodo/rdd4/bygul_simulations_bronko/rsv_nextstrain/rsva_nextstrain_metadata_08192026.tsv", sep="\t")
metadata

,accession,strain,date,PPX_accession,PPX_accession__url,INSDC_accession,INSDC_accession__url,region,country,division,...,qc.overallScore,qc.overallStatus,missing_data,alignmentScore,alignmentStart,alignmentEnd,genome_coverage,cdsCoverage,F_coverage,G_coverage
0,PP_0015PZ1,Japan/NG-016-04/2004-10-28,2004-10-28,PP_0015PZ1.2,https://pathoplexus.org/seq/PP_0015PZ1.2,AB470478.1,https://www.ncbi.nlm.nih.gov/nuccore/AB470478.1,Asia,Japan,Niigata,...,0.000000,good,0,750,5285,5626,0.022463,G:0.3447204968944099,0.00000,0.344720
1,PP_0015Q0Z,Japan/NG-082-05/2005-12-09,2005-12-09,PP_0015Q0Z.2,https://pathoplexus.org/seq/PP_0015Q0Z.2,AB470479.1,https://www.ncbi.nlm.nih.gov/nuccore/AB470479.1,Asia,Japan,Niigata,...,0.000000,good,0,735,5285,5626,0.022463,G:0.3447204968944099,0.00000,0.344720
2,PP_0015Q1X,Japan/PP_0015Q1X.1/unknown,XXXX-XX-XX,PP_0015Q1X.1,https://pathoplexus.org/seq/PP_0015Q1X.1,AB485783.1,https://www.ncbi.nlm.nih.gov/nuccore/AB485783.1,Asia,Japan,Okinawa,...,0.000000,good,0,1070,5168,5626,0.030148,G:0.4658385093167702,0.00000,0.465839
3,PP_0015Q2V,Japan/PP_0015Q2V.1/unknown,XXXX-XX-XX,PP_0015Q2V.1,https://pathoplexus.org/seq/PP_0015Q2V.1,AB485784.1,https://www.ncbi.nlm.nih.gov/nuccore/AB485784.1,Asia,Japan,Okinawa,...,0.000000,good,0,1098,5168,5626,0.030148,G:0.4658385093167702,0.00000,0.465839
4,PP_0015Q3T,Japan/PP_0015Q3T.1/unknown,XXXX-XX-XX,PP_0015Q3T.1,https://pathoplexus.org/seq/PP_0015Q3T.1,AB485785.1,https://www.ncbi.nlm.nih.gov/nuccore/AB485785.1,Asia,Japan,Okinawa,...,0.000000,good,0,1098,5168,5626,0.030148,G:0.4658385093167702,0.00000,0.465839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39121,PP_007CARA,India/PP_007CARA.1/2024-10-10,2024-10-10,PP_007CARA.1,https://pathoplexus.org/seq/PP_007CARA.1,PZ794760.1,https://www.ncbi.nlm.nih.gov/nuccore/PZ794760.1,Asia,India,Karnataka,...,0.000000,good,0,1621,5291,5869,0.038030,"F:0.09913043478260869,G:0.3385093167701863",0.09913,0.338509
39122,PP_007CAT6,India/PP_007CAT6.1/2024-11-12,2024-11-12,PP_007CAT6.1,https://pathoplexus.org/seq/PP_007CAT6.1,PZ794762.1,https://www.ncbi.nlm.nih.gov/nuccore/PZ794762.1,Asia,India,Karnataka,...,0.000000,good,0,1629,5291,5869,0.038030,"F:0.09913043478260869,G:0.3385093167701863",0.09913,0.338509
39123,PP_007CAV2,India/PP_007CAV2.1/2024-11-16,2024-11-16,PP_007CAV2.1,https://pathoplexus.org/seq/PP_007CAV2.1,PZ794764.1,https://www.ncbi.nlm.nih.gov/nuccore/PZ794764.1,Asia,India,Karnataka,...,0.000000,good,0,1625,5291,5869,0.038030,"F:0.09913043478260869,G:0.3385093167701863",0.09913,0.338509
39124,PP_007CAU4,India/PP_007CAU4.1/2024-11-14,2024-11-14,PP_007CAU4.1,https://pathoplexus.org/seq/PP_007CAU4.1,PZ794763.1,https://www.ncbi.nlm.nih.gov/nuccore/PZ794763.1,Asia,India,Karnataka,...,0.000000,good,0,1629,5291,5869,0.038030,"F:0.09913043478260869,G:0.3385093167701863",0.09913,0.338509
39125,PP_007CALL,USA/V26005833/2026-05-26,2026-05-26,PP_007CALL.1,https://pathoplexus.org/seq/PP_007CALL.1,PZ777364.1,https://www.ncbi.nlm.nih.gov/nuccore/PZ777364.1,North America,USA,New Jersey,...,0.751111,good,0,44681,6,15208,0.998555,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.00000,1.000000

In [6]:
metadata.columns

Index(['accession', 'strain', 'date', 'PPX_accession', 'PPX_accession__url',
       'INSDC_accession', 'INSDC_accession__url', 'region', 'country',
       'division', 'location', 'host', 'date_submitted', 'sra_accession',
       'authors', 'institution', 'dataUseTerms', 'dataUseTerms__url',
       'restrictedUntil', 'clade', 'escape', 'qc.overallScore',
       'qc.overallStatus', 'missing_data', 'alignmentScore', 'alignmentStart',
       'alignmentEnd', 'genome_coverage', 'cdsCoverage', 'F_coverage',
       'G_coverage'],
      dtype='str')

In [12]:
## Quality control for full coverage sequences
complete_genomes_metadata = metadata[(metadata['genome_coverage'] == 1.0) & (metadata['missing_data'] == 0)]
complete_genomes_metadata = complete_genomes_metadata[~complete_genomes_metadata['date'].str.contains('X')]
complete_genomes_metadata

,accession,strain,date,PPX_accession,PPX_accession__url,INSDC_accession,INSDC_accession__url,region,country,division,...,qc.overallScore,qc.overallStatus,missing_data,alignmentScore,alignmentStart,alignmentEnd,genome_coverage,cdsCoverage,F_coverage,G_coverage
2934,PP_0019D3W,Netherlands/01-002215/2001-01-24,2001-01-24,PP_0019D3W.1,https://pathoplexus.org/seq/PP_0019D3W.1,JQ901450.1,https://www.ncbi.nlm.nih.gov/nuccore/JQ901450.1,Europe,Netherlands,NaN,...,0.0,good,0,42779,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0
2938,PP_0019D10,Netherlands/01-000583/2001-01-07,2001-01-07,PP_0019D10.2,https://pathoplexus.org/seq/PP_0019D10.2,JQ901448.1,https://www.ncbi.nlm.nih.gov/nuccore/JQ901448.1,Europe,Netherlands,NaN,...,0.0,good,0,42741,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0
2939,PP_0019D4U,Netherlands/01-002279/2001-01-24,2001-01-24,PP_0019D4U.1,https://pathoplexus.org/seq/PP_0019D4U.1,JQ901451.1,https://www.ncbi.nlm.nih.gov/nuccore/JQ901451.1,Europe,Netherlands,NaN,...,0.0,good,0,42724,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0
2940,PP_0019D6Q,Netherlands/02-000110/2002-01-03,2002-01-03,PP_0019D6Q.1,https://pathoplexus.org/seq/PP_0019D6Q.1,JQ901453.1,https://www.ncbi.nlm.nih.gov/nuccore/JQ901453.1,Europe,Netherlands,NaN,...,0.0,good,0,44015,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0
2941,PP_0019D7N,Netherlands/02-00291/2002-01-04,2002-01-04,PP_0019D7N.1,https://pathoplexus.org/seq/PP_0019D7N.1,JQ901454.1,https://www.ncbi.nlm.nih.gov/nuccore/JQ901454.1,Europe,Netherlands,NaN,...,0.0,good,0,42718,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38917,PP_0078PWV,Peru/PP_0078PWV.1/2024-05-06,2024-05-06,PP_0078PWV.1,https://pathoplexus.org/seq/PP_0078PWV.1,PZ645683.1,https://www.ncbi.nlm.nih.gov/nuccore/PZ645683.1,South America,Peru,Lima,...,0.0,good,0,44840,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0
38919,PP_0078PXT,Peru/PP_0078PXT.1/2024-05-20,2024-05-20,PP_0078PXT.1,https://pathoplexus.org/seq/PP_0078PXT.1,PZ645684.1,https://www.ncbi.nlm.nih.gov/nuccore/PZ645684.1,South America,Peru,Lima,...,0.0,good,0,44836,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0
39020,PP_0079F4L,Viet_Nam/HCM-VCM-260708309/2026-07-09,2026-07-09,PP_0079F4L.1,https://pathoplexus.org/seq/PP_0079F4L.1,PZ705313.1,https://www.ncbi.nlm.nih.gov/nuccore/PZ705313.1,Asia,Vietnam,Hochiminh,...,0.0,good,0,44696,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0
39054,PP_007AA8F,Switzerland/PP_007AA8F.1/2024-11-21,2024-11-21,PP_007AA8F.1,https://pathoplexus.org/seq/PP_007AA8F.1,OZ501198.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ501198.1,Europe,Switzerland,NaN,...,0.0,good,0,44703,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0
39062,PP_007AA9D,Switzerland/PP_007AA9D.1/2025-01-03,2025-01-03,PP_007AA9D.1,https://pathoplexus.org/seq/PP_007AA9D.1,OZ501199.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ501199.1,Europe,Switzerland,Not Provided,...,0.0,good,0,44801,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0

In [19]:
## partition by month and clade
complete_genomes_metadata['month'] = pd.to_datetime(complete_genomes_metadata['date']).dt.to_period('M')

In [30]:
##group by month and clade and return first
selected = complete_genomes_metadata.sort_values(by='date')[['month', 'clade', 'INSDC_accession', 'PPX_accession']].groupby(['month', 'clade']).first().reset_index()
selected

       month    clade INSDC_accession PPX_accession
0    1998-03      A.3      JX069801.1  PP_0019EBD.2
1    1998-10    A.2.1      KF826823.1  PP_001B7QP.2
2    2001-01    A.2.1      JQ901451.1  PP_0019D4U.1
3    2001-01  A.2.1.1      JQ901448.1  PP_0019D10.2
4    2001-03      A.3      JX069799.1  PP_0019E9H.2
..       ...      ...             ...           ...
538  2026-02  A.D.3.7      OZ474779.1  PP_006X30W.1
539  2026-03  A.D.1.4      OZ474774.1  PP_006X3V5.1
540  2026-03  A.D.5.2      OZ474803.1  PP_006X3YZ.1
541  2026-04  A.D.3.3      OZ474787.1  PP_006X42R.1
542  2026-07  A.D.3.1      PZ705313.1  PP_0079F4L.1

[543 rows x 4 columns]

In [32]:
from Bio import SeqIO

fasta_file = "/dodo/rdd4/bygul_simulations_bronko/rsv_nextstrain/rsva_nextstrain_seqs_08192026.fasta"
output_dir = "/dodo/rdd4/bygul_simulations_bronko/rsv_nextstrain/"

# Load FASTA sequences into a dictionary
records = {
    record.id.split(".")[0]: record
    for record in SeqIO.parse(fasta_file, "fasta")
}

for _, row in selected.iterrows():
    accession = row["PPX_accession"].split(".")[0]

    if accession not in records:
        print(f"Warning: {accession} not found")
        continue

    # Header / filename
    label = f"{accession}_{row['clade']}_{row['month']}"

    # Make a copy so we don't modify the original record
    record = records[accession][:]
    record.id = label
    record.name = label
    record.description = ""

    # Write individual FASTA
    SeqIO.write(
        record,
        f"{output_dir}{label}.fasta",
        "fasta"
    )

In [35]:
## Selecting clades for simulations

In [34]:
complete_genomes_metadata.value_counts('clade')

clade
A.D          282
A.D.3        241
A.D.1        239
A.D.5.2       94
A.D.2.2       76
A.D.5         71
A.3.1         59
A.D.1.8       47
A.D.3.4       38
A.D.1.4       38
A.D.4.1       37
A.D.1.5       32
A.3.1.1       31
A.D.3.7       31
A.D.1.9       29
A.D.2.1       29
A.D.2.2.1     24
A.D.1.6       24
A.D.1.3       21
A.D.5.1       16
A.D.5.3       16
A.2.1.1       15
A.D.3.3       13
A.D.1.11      12
A.D.1.10      12
A.D.1.7       11
A.D.3.1       10
A.D.3.10      10
A.D.3.11      10
A.2.1          8
A.3            7
A.D.3.2        7
A.D.3.12       6
A.D.2          3
A.D.3.5        2
A              1
A.D.4          1
A.D.3.9        1
A.D.1.2        1
Name: count, dtype: int64

In [47]:
simulated_tree_data = complete_genomes_metadata[(complete_genomes_metadata['date'] > '2025-01-01') & (complete_genomes_metadata['clade'] == 'A.D.3.7')]
simulated_tree_data

,accession,strain,date,PPX_accession,PPX_accession__url,INSDC_accession,INSDC_accession__url,region,country,division,...,qc.overallStatus,missing_data,alignmentScore,alignmentStart,alignmentEnd,genome_coverage,cdsCoverage,F_coverage,G_coverage,month
30679,PP_002XX4Y,Ireland/PP_002XX4Y.1/2025-03-31,2025-03-31,PP_002XX4Y.1,https://pathoplexus.org/seq/PP_002XX4Y.1,OZ262273.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ262273.1,Europe,Ireland,NaN,...,good,0,44760,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2025-03
30682,PP_002XX7S,Ireland/PP_002XX7S.1/2025-04-03,2025-04-03,PP_002XX7S.1,https://pathoplexus.org/seq/PP_002XX7S.1,OZ262264.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ262264.1,Europe,Ireland,NaN,...,good,0,44773,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2025-04
33480,PP_003V05W,Switzerland/PP_003V05W.2/2025-01-28,2025-01-28,PP_003V05W.2,https://pathoplexus.org/seq/PP_003V05W.2,OZ272668.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ272668.1,Europe,Switzerland,NaN,...,good,0,44772,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2025-01
33481,PP_003V06U,Switzerland/PP_003V06U.2/2025-02-11,2025-02-11,PP_003V06U.2,https://pathoplexus.org/seq/PP_003V06U.2,OZ272704.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ272704.1,Europe,Switzerland,NaN,...,good,0,44788,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2025-02
33509,PP_003V105,Slovakia/RNA/2025-03-19,2025-03-19,PP_003V105.2,https://pathoplexus.org/seq/PP_003V105.2,OZ274128.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ274128.1,Europe,Slovakia,NaN,...,good,0,44751,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2025-03
33510,PP_003V113,Slovakia/RNA/2025-03-19,2025-03-19,PP_003V113.2,https://pathoplexus.org/seq/PP_003V113.2,OZ274129.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ274129.1,Europe,Slovakia,NaN,...,good,0,44751,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2025-03
35811,PP_004J6CX,Ireland/PP_004J6CX.1/2025-11-20,2025-11-20,PP_004J6CX.1,https://pathoplexus.org/seq/PP_004J6CX.1,OZ409238.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ409238.1,Europe,Ireland,NaN,...,good,0,44768,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2025-11
36305,PP_004KZPD,Ireland/PP_004KZPD.1/2025-12-29,2025-12-29,PP_004KZPD.1,https://pathoplexus.org/seq/PP_004KZPD.1,OZ414564.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ414564.1,Europe,Ireland,NaN,...,good,0,44746,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2025-12
36314,PP_004KZXX,Ireland/PP_004KZXX.1/2026-01-13,2026-01-13,PP_004KZXX.1,https://pathoplexus.org/seq/PP_004KZXX.1,OZ414554.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ414554.1,Europe,Ireland,NaN,...,good,0,44756,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2026-01
36320,PP_004L03H,Ireland/PP_004L03H.1/2025-12-31,2025-12-31,PP_004L03H.1,https://pathoplexus.org/seq/PP_004L03H.1,OZ414578.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ414578.1,Europe,Ireland,NaN,...,good,0,44754,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2025-12
36328,PP_004L0B1,Ireland/PP_004L0B1.1/2026-01-02,2026-01-02,PP_004L0B1.1,https://pathoplexus.org/seq/PP_004L0B1.1,OZ414568.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ414568.1,Europe,Ireland,NaN,...,good,0,44730,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2026-01
37895,PP_006TT8Y,Ireland/PP_006TT8Y.1/2026-01-09,2026-01-09,PP_006TT8Y.1,https://pathoplexus.org/seq/PP_006TT8Y.1,OZ457522.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ457522.1,Europe,Ireland,NaN,...,good,0,44750,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2026-01
37907,PP_006TTJB,Ireland/PP_006TTJB.1/2025-12-14,2025-12-14,PP_006TTJB.1,https://pathoplexus.org/seq/PP_006TTJB.1,OZ457501.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ457501.1,Europe,Ireland,NaN,...,good,0,44724,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2025-12
37916,PP_006TTTT,Ireland/PP_006TTTT.1/2025-12-29,2025-12-29,PP_006TTTT.1,https://pathoplexus.org/seq/PP_006TTTT.1,OZ457493.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ457493.1,Europe,Ireland,NaN,...,good,0,44752,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2025-12
37937,PP_006TUEK,Ireland/PP_006TUEK.1/2026-01-26,2026-01-26,PP_006TUEK.1,https://pathoplexus.org/seq/PP_006TUEK.1,OZ457532.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ457532.1,Europe,Ireland,NaN,...,good,0,44720,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2026-01
37948,PP_006TUK8,Ireland/PP_006TUK8.1/2025-11-24,2025-11-24,PP_006TUK8.1,https://pathoplexus.org/seq/PP_006TUK8.1,OZ457502.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ457502.1,Europe,Ireland,NaN,...,good,0,44744,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2025-11
38504,PP_006X2X2,Ireland/PP_006X2X2.1/2026-01-26,2026-01-26,PP_006X2X2.1,https://pathoplexus.org/seq/PP_006X2X2.1,OZ474785.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ474785.1,Europe,Ireland,NaN,...,good,0,44736,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2026-01
38507,PP_006X30W,Ireland/PP_006X30W.1/2026-02-08,2026-02-08,PP_006X30W.1,https://pathoplexus.org/seq/PP_006X30W.1,OZ474779.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ474779.1,Europe,Ireland,NaN,...,good,0,44736,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2026-02
38524,PP_006X3HV,Ireland/PP_006X3HV.1/2026-02-08,2026-02-08,PP_006X3HV.1,https://pathoplexus.org/seq/PP_006X3HV.1,OZ474789.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ474789.1,Europe,Ireland,NaN,...,good,0,44736,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2026-02
38529,PP_006X3MM,Ireland/PP_006X3MM.1/2026-02-16,2026-02-16,PP_006X3MM.1,https://pathoplexus.org/seq/PP_006X3MM.1,OZ474778.1,https://www.ncbi.nlm.nih.gov/nuccore/OZ474778.1,Europe,Ireland,NaN,...,good,0,44724,1,15225,1.0,"F:1,G:1,L:1,M:1,M2-1:1,M2-2:1,N:1,NS1:1,NS2:1,...",1.0,1.0,2026-02

In [50]:
from Bio import SeqIO

fasta_file = "/dodo/rdd4/bygul_simulations_bronko/rsv_nextstrain/rsva_nextstrain_seqs_08192026.fasta"
output_dir = "/dodo/rdd4/bygul_simulations_bronko/rsv_nextstrain/rsva_outbreak_sequences/sequences/"

# Load FASTA sequences into a dictionary
records = {
    record.id.split(".")[0]: record
    for record in SeqIO.parse(fasta_file, "fasta")
}

for _, row in simulated_tree_data.iterrows():
    accession = row["PPX_accession"].split(".")[0]

    if accession not in records:
        print(f"Warning: {accession} not found")
        continue

    # Header / filename
    label = f"{accession}_{row['clade']}_{row['month']}"

    # Make a copy so we don't modify the original record
    record = records[accession][:]
    record.id = label
    record.name = label
    record.description = ""

    # Write individual FASTA
    SeqIO.write(
        record,
        f"{output_dir}{label}.fasta",
        "fasta"
    )