In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
parsnp_data = pd.read_csv('/home/Users/rdd4/bronko_test/alignment_comparisons/sars_evolution_results/parsnp_consensus/parsnp.vcf', delimiter='\t', skiprows=5)

In [3]:
parsnp_data[~parsnp_data['ALT'].isin(['A','C','G','T'])]

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,ancestral_sequence.fa.ref,...,1090-3570-0.112577.fasta,615-4521-0.135056.fasta,1259-2239-0.113884.fasta,1310-528-0.101914.fasta,1463-6825-0.109307.fasta,1848-5370-0.093392.fasta,199-99-0.164007.fasta,2189-5218-0.051769.fasta,1067-6768-0.116656.fasta,1373-6524-0.105837.fasta
26,Ancestral,1567,CATAGAACTG.CGTTTAAGAT,C,"A,T",40,PASS,NaN,GT,0,...,0,0,0,0,0,0,0,0,0,0
189,Ancestral,10406,GCTCTTTAGG.TATTCATAGC,T,"G,C",40,PASS,NaN,GT,0,...,0,0,0,0,0,0,0,0,0,0
238,Ancestral,13357,CACTTGTGAA.ATAACACTTG,A,"G,C",40,PASS,NaN,GT,0,...,0,0,0,0,0,0,0,0,0,0
242,Ancestral,13694,CACAAATGGC.TATCTGATTT,T,"G,C",40,PASS,NaN,GT,0,...,0,0,0,0,0,0,0,0,0,0
302,Ancestral,15968,TATAATTCAG.GAATAATCAT,G,"T,A",40,PASS,NaN,GT,0,...,0,0,0,0,0,0,0,0,0,0
371,Ancestral,19710,AGAGTGCTGC.AATTTTTGAT,A,"T,G",40,PASS,NaN,GT,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df = parsnp_data
df['alt_index_list'] = df['ALT'].apply(lambda alts: list(range(1, len(alts)+1)))
df = df.explode(['ALT', 'alt_index_list']).reset_index(drop=True)
df['alt_index_list'] = df['alt_index_list'].astype(int)

# 2️⃣ fix fasta columns
for col in fasta_cols:
    df[col] = (df[col] == df['alt_index_list']).astype(int)

# 3️⃣ cleanup
df = df.drop(columns='alt_index_list')

In [4]:
parsnp_data['POS'] = parsnp_data['POS'].astype(int)

In [8]:
import os
import pandas as pd

vcf_dir = "/home/Users/rdd4/bronko_test/alignment_comparisons/sars_evolution_results/bronko_single_ref"  # change this to your VCF folder path
vcf_files = [f for f in os.listdir(vcf_dir) if f.endswith(".vcf")]


variant_dict = {}

for vcf_file in vcf_files:
    sample_name = vcf_file.replace(".vcf", ".fasta")
    with open(os.path.join(vcf_dir, vcf_file)) as f:
        for line in f:
            if line.startswith("#"):
                continue
            fields = line.strip().split("\t")
            chrom, pos, _, ref, alt = fields[:5]
            key = (chrom, pos, ref, alt)
            if key not in variant_dict:
                variant_dict[key] = {}
            variant_dict[key][sample_name] = 1
            
print(variant_dict)

# convert to DataFrame

bronko = pd.DataFrame.from_dict(variant_dict, orient="index")
bronko = bronko.fillna(0).astype(int)
bronko.reset_index(inplace=True)
bronko.rename(columns={"index": ["CHROM", "POS", "REF", "ALT"]}, inplace=True)

new_names = ['#CHROM','POS','REF','ALT']
bronko.columns = new_names + bronko.columns[4:].tolist()
bronko['POS'] = bronko['POS'].astype(int)
bronko

# df = bronko.drop(columns='index')

# # save table

# # df.to_csv("variant_presence_matrix.csv", index=False)
# print("Saved variant presence matrix to variant_presence_matrix.csv")

{('Ancestral', '6388', 'T', 'C'): {'659-7827-0.129215.fasta': 1, '199-99-0.164007.fasta': 1, '286-3036-0.159561.fasta': 1, '1174-9602-0.106911.fasta': 1, '765-6965-0.125270.fasta': 1, '16-3743-0.240767.fasta': 1, '2024-1707-0.066030.fasta': 1, '1416-9856-0.087780.fasta': 1, '733-3924-0.128434.fasta': 1, '1839-6616-0.071935.fasta': 1, '1708-461-0.086237.fasta': 1, '1738-41-0.089304.fasta': 1, '499-1187-0.148721.fasta': 1, '410-7883-0.145812.fasta': 1, '529-1386-0.161001.fasta': 1, '1989-3131-0.067958.fasta': 1, '1745-63-0.082769.fasta': 1, '993-2379-0.141732.fasta': 1, '1816-445-0.086718.fasta': 1, '959-5503-0.109298.fasta': 1, '212-3391-0.190811.fasta': 1, '1064-5598-0.110931.fasta': 1, '796-573-0.117259.fasta': 1, '806-2593-0.137712.fasta': 1, '1735-8837-0.075900.fasta': 1, '870-3005-0.126122.fasta': 1, '1809-1763-0.092410.fasta': 1, '1548-3006-0.095750.fasta': 1, '476-2467-0.161842.fasta': 1, '903-4365-0.125545.fasta': 1, '50-661-0.219629.fasta': 1, '1921-2343-0.072007.fasta': 1, '1507-380-0.086553.fasta': 1, '1626-3448-0.089205.fasta': 1, '554-2356-0.145751.fasta': 1, '663-9278-0.131761.fasta': 1, '202-4238-0.169615.fasta': 1, '208-6591-0.176254.fasta': 1, '900-9352-0.118927.fasta': 1, '1859-3090-0.084843.fasta': 1, '252-340-0.183732.fasta': 1, '2030-5143-0.115054.fasta': 1, '164-570-0.170736.fasta': 1, '94-2855-0.199494.fasta': 1, '468-990-0.148467.fasta': 1, '1187-1443-0.140515.fasta': 1, '28-3201-0.240991.fasta': 1, '1304-5744-0.094229.fasta': 1, '838-4735-0.117713.fasta': 1, '1218-1812-0.099859.fasta': 1, '1435-5104-0.100572.fasta': 1, '1583-2203-0.093116.fasta': 1, '749-1091-0.134642.fasta': 1, '448-3394-0.139610.fasta': 1, '1755-4972-0.081716.fasta': 1, '56-7723-0.212086.fasta': 1, '1062-2354-0.117560.fasta': 1, '1822-319-0.075796.fasta': 1, '463-1596-0.134555.fasta': 1, '604-1410-0.149605.fasta': 1, '778-2145-0.125808.fasta': 1, '726-4731-0.118448.fasta': 1, '254-4470-0.160258.fasta': 1, '1504-240-0.091670.fasta': 1, '786-2932-0.124891.fasta': 1, '319-2472-0.177487.fasta': 1, '979-430-0.113077.fasta': 1, '1049-8208-0.111373.fasta': 1, '505-3176-0.143186.fasta': 1, '1178-8796-0.110522.fasta': 1, '1135-5739-0.104982.fasta': 1, '1308-7106-0.102226.fasta': 1, '176-9548-0.171243.fasta': 1, '129-9273-0.190098.fasta': 1, '537-8099-0.135958.fasta': 1, '53-9620-0.209780.fasta': 1, '634-2216-0.143387.fasta': 1, '72-1406-0.219398.fasta': 1, '680-5029-0.121259.fasta': 1, '1614-8893-0.091330.fasta': 1, '1526-123-0.096773.fasta': 1, '1890-241-0.084194.fasta': 1, '687-1150-0.121593.fasta': 1, '1565-2261-0.087986.fasta': 1, '628-8097-0.121129.fasta': 1, '109-4380-0.200548.fasta': 1, '1090-3570-0.112577.fasta': 1, '676-6634-0.138976.fasta': 1, '1719-554-0.083996.fasta': 1, '169-1727-0.187163.fasta': 1, '2065-4633-0.068197.fasta': 1, '1073-3777-0.121039.fasta': 1, '312-6814-0.174227.fasta': 1, '1468-394-0.086638.fasta': 1, '86-9356-0.186004.fasta': 1, '1413-80-0.121555.fasta': 1, '1128-4551-0.105291.fasta': 1, '314-7765-0.149513.fasta': 1, '867-5973-0.128262.fasta': 1, '1991-5165-0.086513.fasta': 1, '1121-1649-0.103801.fasta': 1, '1763-1101-0.092203.fasta': 1, '557-718-0.146418.fasta': 1, '46-764-0.226142.fasta': 1, '1245-2556-0.109515.fasta': 1, '375-8578-0.157388.fasta': 1, '944-6220-0.113651.fasta': 1, '1466-8215-0.110049.fasta': 1, '275-9559-0.174972.fasta': 1, '345-49-0.153309.fasta': 1, '290-3469-0.153326.fasta': 1, '96-3723-0.184796.fasta': 1, '1521-72-0.098443.fasta': 1, '908-587-0.121781.fasta': 1, '1226-2624-0.107281.fasta': 1, '183-4105-0.174581.fasta': 1, '571-5166-0.132729.fasta': 1, '338-7649-0.151037.fasta': 1, '1593-1414-0.091119.fasta': 1, '975-4133-0.123311.fasta': 1, '1252-1935-0.122450.fasta': 1, '1238-6229-0.113420.fasta': 1, '1280-3558-0.108520.fasta': 1, '487-7067-0.137145.fasta': 1, '1380-3674-0.112141.fasta': 1, '180-1648-0.167749.fasta': 1, '373-2308-0.154348.fasta': 1, '612-9405-0.136684.fasta': 1, '89-9100-0.189183.fasta': 1, '162-9742-0.179283.fasta': 1, '1690-6347-0.082253.fasta': 1, '801-2967-0.115346.fasta': 1, '1003-1279-0.116832.fasta': 1, '232-497-0.189854.fasta': 1, '891-467-0.132008.fasta': 1, '307-1619-0.158478.fasta': 1, '615-4521-0.135056.fasta': 1, '331-581-0.147482.fasta': 1, '1449-790-0.093140.fasta': 1, '831-8428-0.148615.fasta': 1, '928-5581-0.113517.fasta': 1, '157-3040-0.173201.fasta': 1, '1424-2940-0.088586.fasta': 1, '1300-1264-0.091930.fasta': 1, '114-8685-0.191462.fasta': 1, '851-318-0.127022.fasta': 1, '12-9955-0.252646.fasta': 1, '1512-6150-0.110121.fasta': 1, '1773-3745-0.140783.fasta': 1, '103-7787-0.207010.fasta': 1, '25-6537-0.227496.fasta': 1, '333-7357-0.153714.fasta': 1, '123-7152-0.182474.fasta': 1, '519-3427-0.154623.fasta': 1, '1259-2239-0.113884.fasta': 1, '781-3218-0.128665.fasta': 1, '1397-793-0.103471.fasta': 1, '408-3719-0.153856.fasta': 1, '1702-2107-0.088731.fasta': 1, '626-952-0.128458.fasta': 1, '1196-569-0.109762.fasta': 1, '1140-579-0.104124.fasta': 1, '8-1685-0.245467.fasta': 1, '981-4867-0.111129.fasta': 1, '1539-867-0.097263.fasta': 1, '403-3021-0.147967.fasta': 1, '269-4651-0.157289.fasta': 1, '1310-528-0.101914.fasta': 1, '846-483-0.117237.fasta': 1, '1213-8538-0.116681.fasta': 1, '133-9455-0.182645.fasta': 1, '1027-5050-0.136504.fasta': 1, '1240-2660-0.104449.fasta': 1, '1561-6239-0.090921.fasta': 1, '357-4497-0.149777.fasta': 1, '446-9369-0.138305.fasta': 1, '875-4751-0.134985.fasta': 1, '1444-1508-0.090271.fasta': 1, '1563-157-0.103706.fasta': 1, '1011-3429-0.117502.fasta': 1, '229-7387-0.162579.fasta': 1, '335-3063-0.188735.fasta': 1, '532-6438-0.129312.fasta': 1, '1161-7303-0.101514.fasta': 1, '1144-5960-0.114009.fasta': 1, '1433-5796-0.098966.fasta': 1, '371-2086-0.145488.fasta': 1, '933-2751-0.118706.fasta': 1, '1265-7046-0.118915.fasta': 1, '390-5548-0.150688.fasta': 1, '186-6008-0.171893.fasta': 1, '517-6048-0.139684.fasta': 1, '118-813-0.179278.fasta': 1, '1854-720-0.089883.fasta': 1, '641-737-0.136024.fasta': 1, '525-1307-0.141324.fasta': 1, '1411-4639-0.110231.fasta': 1, '1470-7104-0.109600.fasta': 1, '718-1764-0.126225.fasta': 1, '66-4381-0.208403.fasta': 1, '1228-8794-0.122785.fasta': 1, '1255-7082-0.106031.fasta': 1, '1757-1675-0.078395.fasta': 1, '1383-301-0.120632.fasta': 1, '2038-10-0.078370.fasta': 1, '1082-674-0.108537.fasta': 1, '1427-5102-0.103391.fasta': 1, '310-567-0.150005.fasta': 1, '720-3925-0.132045.fasta': 1, '560-5948-0.135073.fasta': 1, '736-419-0.131308.fasta': 1, '1202-4975-0.097154.fasta': 1, '1683-2814-0.091002.fasta': 1, '617-723-0.129367.fasta': 1, '1700-3165-0.085624.fasta': 1, '39-9252-0.218839.fasta': 1, '361-7877-0.176812.fasta': 1, '1420-2368-0.096223.fasta': 1, '37-5563-0.234919.fasta': 1, '197-3738-0.162092.fasta': 1, '1862-162-0.081004.fasta': 1, '1531-633-0.108000.fasta': 1, '580-2398-0.132744.fasta': 1, '1586-9894-0.091767.fasta': 1, '620-1028-0.132514.fasta': 1, '646-1287-0.126452.fasta': 1, '926-1547-0.125724.fasta': 1, '495-1456-0.154614.fasta': 1, '44-8165-0.244689.fasta': 1, '661-8861-0.136214.fasta': 1, '1797-215-0.082853.fasta': 1, '493-2731-0.143231.fasta': 1, '849-7006-0.113334.fasta': 1, '485-172-0.136582.fasta': 1, '1578-5663-0.086951.fasta': 1, '1194-6092-0.110096.fasta': 1, '1022-7910-0.124952.fasta': 1, '418-1069-0.143394.fasta': 1, '823-603-0.117459.fasta': 1, '840-769-0.112757.fasta': 1, '1696-5754-0.089175.fasta': 1, '999-3536-0.117381.fasta': 1, '1207-2443-0.103852.fasta': 1, '1640-3478-0.095560.fasta': 1, '1487-239-0.103639.fasta': 1, '258-266-0.154249.fasta': 1, '235-4294-0.162362.fasta': 1, '946-39-0.109462.fasta': 1, '455-4992-0.145565.fasta': 1, '1638-5805-0.087186.fasta': 1, '804-8758-0.117930.fasta': 1, '412-1783-0.143742.fasta': 1, '2072-3-0.066634.fasta': 1, '483-1336-0.142266.fasta': 1, '1099-9605-0.108772.fasta': 1, '439-342-0.159080.fasta': 1, '1025-4339-0.125081.fasta': 1, '106-2700-0.190300.fasta': 1, '567-539-0.139854.fasta': 1, '941-565-0.109830.fasta': 1, '1545-444-0.111446.fasta': 1, '674-4893-0.129073.fasta': 1, '1167-962-0.110990.fasta': 1, '145-4043-0.177413.fasta': 1, '1623-3824-0.099101.fasta': 1, '303-292-0.166174.fasta': 1, '707-7325-0.120203.fasta': 1, '587-9174-0.144834.fasta': 1, '758-1209-0.126513.fasta': 1, '2028-781-0.070886.fasta': 1, '860-3270-0.131817.fasta': 1, '608-7050-0.133622.fasta': 1, '810-2678-0.113335.fasta': 1, '919-3338-0.117785.fasta': 1, '1674-231-0.095453.fasta': 1, '1155-2475-0.109870.fasta': 1, '938-109-0.120151.fasta': 1, '154-4890-0.173415.fasta': 1, '2121-4459-0.064140.fasta': 1, '1844-169-0.072437.fasta': 1, '1483-2200-0.132799.fasta': 1, '767-5857-0.128956.fasta': 1, '265-8349-0.161768.fasta': 1, '248-6854-0.168706.fasta': 1, '589-8726-0.143757.fasta': 1, '843-8466-0.126061.fasta': 1, '1224-7823-0.108075.fasta': 1, '1431-9885-0.092113.fasta': 1, '1287-6653-0.095228.fasta': 1, '1852-2110-0.149486.fasta': 1, '1110-2464-0.113581.fasta': 1, '1088-463-0.123335.fasta': 1, '427-5889-0.140839.fasta': 1}, ('Ancestral', '10352', 'C', 'T'): {'659-7827-0.129215.fasta': 1}, ('Ancestral', '10406', 'T', 'C'): {'659-7827-0.129215.fasta': 1}, ('Ancestral', '10624', 'C', 'T'): {'659-7827-0.129215.fasta': 1, '199-99-0.164007.fasta': 1, '286-3036-0.159561.fasta': 1, '1174-9602-0.106911.fasta': 1, '765-6965-0.125270.fasta': 1, '1884-1111-0.102719.fasta': 1, '111-664-0.184610.fasta': 1, '16-3743-0.240767.fasta': 1, '1537-6216-0.092969.fasta': 1, '833-766-0.141370.fasta': 1, '2024-1707-0.066030.fasta': 1, '1782-8775-0.110743.fasta': 1, '1416-9856-0.087780.fasta': 1, '733-3924-0.128434.fasta': 1, '1839-6616-0.071935.fasta': 1, '0-6474-0.280390.fasta': 1, '1708-461-0.086237.fasta': 1, '359-624-0.153360.fasta': 1, '460-3567-0.144011.fasta': 1, '1738-41-0.089304.fasta': 1, '1894-932-0.072337.fasta': 1, '205-4955-0.161523.fasta': 1, '1386-7913-0.098710.fasta': 1, '499-1187-0.148721.fasta': 1, '410-7883-0.145812.fasta': 1, '529-1386-0.161001.fasta': 1, '1989-3131-0.067958.fasta': 1, '1745-63-0.082769.fasta': 1, '993-2379-0.141732.fasta': 1, '1816-445-0.086718.fasta': 1, '1209-3484-0.106632.fasta': 1, '600-2998-0.134211.fasta': 1, '141-7287-0.176708.fasta': 1, '2185-516-0.035892.fasta': 1, '959-5503-0.109298.fasta': 1, '1463-6825-0.109307.fasta': 1, '212-3391-0.190811.fasta': 1, '1997-249-0.074381.fasta': 1, '1933-3238-0.067444.fasta': 1, '1317-2100-0.093073.fasta': 1, '273-748-0.159638.fasta': 1, '1064-5598-0.110931.fasta': 1, '796-573-0.117259.fasta': 1, '284-5114-0.162272.fasta': 1, '806-2593-0.137712.fasta': 1, '1232-3172-0.106561.fasta': 1, '349-7561-0.143661.fasta': 1, '1735-8837-0.075900.fasta': 1, '385-5881-0.141656.fasta': 1, '870-3005-0.126122.fasta': 1, '1809-1763-0.092410.fasta': 1, '1548-3006-0.095750.fasta': 1, '789-7810-0.125102.fasta': 1, '569-7114-0.147178.fasta': 1, '476-2467-0.161842.fasta': 1, '903-4365-0.125545.fasta': 1, '50-661-0.219629.fasta': 1, '2033-6484-0.087639.fasta': 1, '2179-5940-0.041073.fasta': 1, '1921-2343-0.072007.fasta': 1, '990-622-0.111062.fasta': 1, '1507-380-0.086553.fasta': 1, '705-6741-0.122437.fasta': 1, '1626-3448-0.089205.fasta': 1, '554-2356-0.145751.fasta': 1, '457-6340-0.148863.fasta': 1, '663-9278-0.131761.fasta': 1, '202-4238-0.169615.fasta': 1, '794-4117-0.131743.fasta': 1, '1874-2972-0.071183.fasta': 1, '1284-3453-0.102658.fasta': 1, '281-125-0.156444.fasta': 1, '241-9558-0.182145.fasta': 1, '305-7638-0.153371.fasta': 1, '208-6591-0.176254.fasta': 1, '545-9930-0.141450.fasta': 1, '900-9352-0.118927.fasta': 1, '1859-3090-0.084843.fasta': 1, '1348-9155-0.107162.fasta': 1, '252-340-0.183732.fasta': 1, '762-976-0.124246.fasta': 1, '1198-3162-0.108545.fasta': 1, '2030-5143-0.115054.fasta': 1, '522-9151-0.130083.fasta': 1, '2195-356-0.032152.fasta': 1, '164-570-0.170736.fasta': 1, '94-2855-0.199494.fasta': 1, '383-2918-0.161629.fasta': 1, '468-990-0.148467.fasta': 1, '2242-2926-0.034278.fasta': 1, '654-9147-0.147749.fasta': 1, '1187-1443-0.140515.fasta': 1, '28-3201-0.240991.fasta': 1, '1304-5744-0.094229.fasta': 1, '838-4735-0.117713.fasta': 1, '1218-1812-0.099859.fasta': 1, '159-7391-0.183015.fasta': 1, '1435-5104-0.100572.fasta': 1, '1583-2203-0.093116.fasta': 1, '749-1091-0.134642.fasta': 1, '448-3394-0.139610.fasta': 1, '416-411-0.147560.fasta': 1, '1755-4972-0.081716.fasta': 1, '576-9362-0.137495.fasta': 1, '1148-681-0.109306.fasta': 1, '1040-970-0.114051.fasta': 1, '56-7723-0.212086.fasta': 1, '1062-2354-0.117560.fasta': 1, '1822-319-0.075796.fasta': 1, '1667-4343-0.097883.fasta': 1, '271-1141-0.156378.fasta': 1, '1841-1524-0.073214.fasta': 1, '463-1596-0.134555.fasta': 1, '131-667-0.185933.fasta': 1, '604-1410-0.149605.fasta': 1, '296-5192-0.166399.fasta': 1, '565-5197-0.131444.fasta': 1, '778-2145-0.125808.fasta': 1, '726-4731-0.118448.fasta': 1, '254-4470-0.160258.fasta': 1, '1504-240-0.091670.fasta': 1, '316-135-0.158834.fasta': 1, '786-2932-0.124891.fasta': 1, '319-2472-0.177487.fasta': 1, '979-430-0.113077.fasta': 1, '1049-8208-0.111373.fasta': 1, '505-3176-0.143186.fasta': 1, '1178-8796-0.110522.fasta': 1, '1135-5739-0.104982.fasta': 1, '887-7500-0.134104.fasta': 1, '1308-7106-0.102226.fasta': 1, '176-9548-0.171243.fasta': 1, '129-9273-0.190098.fasta': 1, '537-8099-0.135958.fasta': 1, '2091-4769-0.058793.fasta': 1, '53-9620-0.209780.fasta': 1, '634-2216-0.143387.fasta': 1, '72-1406-0.219398.fasta': 1, '680-5029-0.121259.fasta': 1, '1614-8893-0.091330.fasta': 1, '394-1017-0.151824.fasta': 1, '239-9274-0.179305.fasta': 1, '1994-8232-0.070494.fasta': 1, '1526-123-0.096773.fasta': 1, '1890-241-0.084194.fasta': 1, '2010-2486-0.064716.fasta': 1, '1595-2319-0.095968.fasta': 1, '687-1150-0.121593.fasta': 1, '2159-2095-0.049811.fasta': 1, '1565-2261-0.087986.fasta': 1, '628-8097-0.121129.fasta': 1, '298-152-0.157300.fasta': 1, '109-4380-0.200548.fasta': 1, '1571-1278-0.087412.fasta': 1, '2191-367-0.040062.fasta': 1, '1090-3570-0.112577.fasta': 1, '2201-6293-0.056341.fasta': 1, '676-6634-0.138976.fasta': 1, '515-2997-0.131760.fasta': 1, '1719-554-0.083996.fasta': 1, '1163-4877-0.124322.fasta': 1, '169-1727-0.187163.fasta': 1, '648-950-0.127158.fasta': 1, '1047-5941-0.111042.fasta': 1, '1101-384-0.119098.fasta': 1, '244-1213-0.202077.fasta': 1, '471-8859-0.139899.fasta': 1, '2065-4633-0.068197.fasta': 1, '1073-3777-0.121039.fasta': 1, '770-6381-0.129148.fasta': 1, '1390-1182-0.113314.fasta': 1, '422-4144-0.168074.fasta': 1, '312-6814-0.174227.fasta': 1, '1468-394-0.086638.fasta': 1, '86-9356-0.186004.fasta': 1, '1314-7158-0.113732.fasta': 1, '490-2821-0.133295.fasta': 1, '1929-51-0.076950.fasta': 1, '1272-5776-0.102128.fasta': 1, '1413-80-0.121555.fasta': 1, '173-1552-0.178052.fasta': 1, '878-1325-0.129263.fasta': 1, '1128-4551-0.105291.fasta': 1, '314-7765-0.149513.fasta': 1, '867-5973-0.128262.fasta': 1, '1991-5165-0.086513.fasta': 1, '1121-1649-0.103801.fasta': 1, '420-7645-0.144285.fasta': 1, '1670-87-0.085233.fasta': 1, '527-770-0.141802.fasta': 1, '1763-1101-0.092203.fasta': 1, '68-1671-0.212316.fasta': 1, '21-1241-0.235038.fasta': 1, '1157-472-0.101546.fasta': 1, '1476-4157-0.109577.fasta': 1, '557-718-0.146418.fasta': 1, '46-764-0.226142.fasta': 1, '1245-2556-0.109515.fasta': 1, '375-8578-0.157388.fasta': 1, '944-6220-0.113651.fasta': 1, '1466-8215-0.110049.fasta': 1, '1395-5727-0.134538.fasta': 1, '275-9559-0.174972.fasta': 1, '345-49-0.153309.fasta': 1, '290-3469-0.153326.fasta': 1, '96-3723-0.184796.fasta': 1, '930-2865-0.107954.fasta': 1, '1521-72-0.098443.fasta': 1, '908-587-0.121781.fasta': 1, '433-4969-0.137484.fasta': 1, '41-471-0.218785.fasta': 1, '1370-7402-0.127165.fasta': 1, '1226-2624-0.107281.fasta': 1, '183-4105-0.174581.fasta': 1, '571-5166-0.132729.fasta': 1, '338-7649-0.151037.fasta': 1, '1593-1414-0.091119.fasta': 1, '2189-5218-0.051769.fasta': 1, '828-1533-0.117079.fasta': 1, '975-4133-0.123311.fasta': 1, '682-6076-0.124199.fasta': 1, '188-9608-0.166862.fasta': 1, '263-2060-0.167351.fasta': 1, '755-6609-0.123060.fasta': 1, '1252-1935-0.122450.fasta': 1, '1238-6229-0.113420.fasta': 1, '10-3523-0.246199.fasta': 1, '1280-3558-0.108520.fasta': 1, '487-7067-0.137145.fasta': 1, '1380-3674-0.112141.fasta': 1, '1277-707-0.137718.fasta': 1, '1037-2326-0.116073.fasta': 1, '180-1648-0.167749.fasta': 1, '373-2308-0.154348.fasta': 1, '612-9405-0.136684.fasta': 1, '89-9100-0.189183.fasta': 1, '425-8066-0.168329.fasta': 1, '162-9742-0.179283.fasta': 1, '1079-4487-0.143224.fasta': 1, '1690-6347-0.082253.fasta': 1, '801-2967-0.115346.fasta': 1, '1003-1279-0.116832.fasta': 1, '322-398-0.150702.fasta': 1, '1126-3703-0.102240.fasta': 1, '396-4097-0.160117.fasta': 1, '232-497-0.189854.fasta': 1, '406-8869-0.149918.fasta': 1, '1818-551-0.108973.fasta': 1, '891-467-0.132008.fasta': 1, '307-1619-0.158478.fasta': 1, '615-4521-0.135056.fasta': 1, '331-581-0.147482.fasta': 1, '1330-8836-0.098664.fasta': 1, '1449-790-0.093140.fasta': 1, '481-9050-0.153455.fasta': 1, '1005-6-0.111093.fasta': 1, '690-2550-0.135574.fasta': 1, '261-5467-0.168674.fasta': 1, '831-8428-0.148615.fasta': 1, '928-5581-0.113517.fasta': 1, '1103-424-0.106836.fasta': 1, '1569-1709-0.088260.fasta': 1, '157-3040-0.173201.fasta': 1, '1424-2940-0.088586.fasta': 1, '2068-5994-0.076659.fasta': 1, '1300-1264-0.091930.fasta': 1, '114-8685-0.191462.fasta': 1, '851-318-0.127022.fasta': 1, '12-9955-0.252646.fasta': 1, '1512-6150-0.110121.fasta': 1, '1773-3745-0.140783.fasta': 1, '59-4927-0.230506.fasta': 1, '103-7787-0.207010.fasta': 1, '25-6537-0.227496.fasta': 1, '333-7357-0.153714.fasta': 1, '84-3693-0.187239.fasta': 1, '123-7152-0.182474.fasta': 1, '166-5463-0.176153.fasta': 1, '1813-9087-0.078854.fasta': 1, '519-3427-0.154623.fasta': 1, '1259-2239-0.113884.fasta': 1, '1876-1743-0.079137.fasta': 1, '224-1686-0.165532.fasta': 1, '1216-2059-0.103901.fasta': 1, '781-3218-0.128665.fasta': 1, '1397-793-0.103471.fasta': 1, '408-3719-0.153856.fasta': 1, '1702-2107-0.088731.fasta': 1, '626-952-0.128458.fasta': 1, '1196-569-0.109762.fasta': 1, '1140-579-0.104124.fasta': 1, '2070-1436-0.066415.fasta': 1, '652-9390-0.138155.fasta': 1, '1902-50-0.076828.fasta': 1, '34-4575-0.228624.fasta': 1, '8-1685-0.245467.fasta': 1, '981-4867-0.111129.fasta': 1, '1539-867-0.097263.fasta': 1, '503-7251-0.149779.fasta': 1, '403-3021-0.147967.fasta': 1, '1492-1715-0.086203.fasta': 1, '2079-2937-0.068457.fasta': 1, '501-9944-0.146231.fasta': 1, '269-4651-0.157289.fasta': 1, '1310-528-0.101914.fasta': 1, '23-4848-0.240759.fasta': 1, '846-483-0.117237.fasta': 1, '1497-1693-0.096950.fasta': 1, '1060-6811-0.134804.fasta': 1, '1213-8538-0.116681.fasta': 1, '133-9455-0.182645.fasta': 1, '1027-5050-0.136504.fasta': 1, '1240-2660-0.104449.fasta': 1, '1561-6239-0.090921.fasta': 1, '1108-6787-0.124635.fasta': 1, '357-4497-0.149777.fasta': 1, '987-4210-0.123844.fasta': 1, '446-9369-0.138305.fasta': 1, '78-6271-0.191502.fasta': 1, '875-4751-0.134985.fasta': 1, '1404-1070-0.101660.fasta': 1, '1444-1508-0.090271.fasta': 1, '1563-157-0.103706.fasta': 1, '1367-8497-0.103366.fasta': 1, '1011-3429-0.117502.fasta': 1, '431-7285-0.165084.fasta': 1, '14-7213-0.246389.fasta': 1, '656-656-0.127469.fasta': 1, '229-7387-0.162579.fasta': 1, '1001-2890-0.153484.fasta': 1, '821-1798-0.120401.fasta': 1, '335-3063-0.188735.fasta': 1, '221-6956-0.169978.fasta': 1, '195-4138-0.173305.fasta': 1, '595-7771-0.128292.fasta': 1, '532-6438-0.129312.fasta': 1, '18-1917-0.235976.fasta': 1, '1161-7303-0.101514.fasta': 1, '1144-5960-0.114009.fasta': 1, '1433-5796-0.098966.fasta': 1, '371-2086-0.145488.fasta': 1, '933-2751-0.118706.fasta': 1, '1447-6197-0.110214.fasta': 1, '1786-8720-0.088003.fasta': 1, '1848-5370-0.093392.fasta': 1, '1265-7046-0.118915.fasta': 1, '120-2163-0.188661.fasta': 1, '1554-560-0.084050.fasta': 1, '630-6233-0.135832.fasta': 1, '906-8826-0.114949.fasta': 1, '390-5548-0.150688.fasta': 1, '186-6008-0.171893.fasta': 1, '1567-1447-0.108882.fasta': 1, '517-6048-0.139684.fasta': 1, '1096-5577-0.103127.fasta': 1, '118-813-0.179278.fasta': 1, '388-5876-0.141592.fasta': 1, '61-1983-0.214267.fasta': 1, '1854-720-0.089883.fasta': 1, '1045-8560-0.106177.fasta': 1, '641-737-0.136024.fasta': 1, '1422-2740-0.106355.fasta': 1, '525-1307-0.141324.fasta': 1, '1411-4639-0.110231.fasta': 1, '1470-7104-0.109

,#CHROM,POS,REF,ALT,659-7827-0.129215.fasta,199-99-0.164007.fasta,286-3036-0.159561.fasta,1174-9602-0.106911.fasta,765-6965-0.125270.fasta,16-3743-0.240767.fasta,...,351-840-0.155096.fasta,638-2612-0.143059.fasta,1616-1813-0.088562.fasta,2-431-0.267960.fasta,1182-6266-0.107268.fasta,5-8929-0.252810.fasta,1032-9555-0.125431.fasta,1529-9021-0.089494.fasta,2250-1-0.009371.fasta,2177-688-0.093981.fasta
0,Ancestral,6388,T,C,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,Ancestral,10352,C,T,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Ancestral,10406,T,C,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Ancestral,10624,C,T,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,0
4,Ancestral,10671,T,C,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
538,Ancestral,23047,G,A,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
539,Ancestral,27571,T,G,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
540,Ancestral,518,T,C,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
541,Ancestral,20610,T,A,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
542,Ancestral,23344,C,T,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [26]:
variant_cols = ["#CHROM", "POS", "REF", "ALT"]
sample_cols = [c for c in bronko.columns if c not in variant_cols]

merged = pd.merge(parsnp_data, bronko, on=variant_cols, how="outer", suffixes=("_1", "_2"))

results = []
for c in sample_cols:
    print(c)
    df1_total = merged[c + "_1"].sum()
    df2_total = merged[c + "_2"].sum()
    shared_snps = ((merged[c + "_1"] == 1) & (merged[c + "_2"] == 1)).sum()
    results.append({"sample": c, "df1_total": df1_total, "df2_total": df2_total, "shared_snps": shared_snps})

overlap_df = pd.DataFrame(results)
overlap_df

659-7827-0.129215.fasta
199-99-0.164007.fasta
286-3036-0.159561.fasta
1174-9602-0.106911.fasta
765-6965-0.125270.fasta
16-3743-0.240767.fasta
2024-1707-0.066030.fasta
1416-9856-0.087780.fasta
733-3924-0.128434.fasta
1839-6616-0.071935.fasta
1708-461-0.086237.fasta
1738-41-0.089304.fasta
499-1187-0.148721.fasta
410-7883-0.145812.fasta
529-1386-0.161001.fasta
1989-3131-0.067958.fasta
1745-63-0.082769.fasta
993-2379-0.141732.fasta
1816-445-0.086718.fasta
959-5503-0.109298.fasta
212-3391-0.190811.fasta
1064-5598-0.110931.fasta
796-573-0.117259.fasta
806-2593-0.137712.fasta
1735-8837-0.075900.fasta
870-3005-0.126122.fasta
1809-1763-0.092410.fasta
1548-3006-0.095750.fasta
476-2467-0.161842.fasta
903-4365-0.125545.fasta
50-661-0.219629.fasta
1921-2343-0.072007.fasta
1507-380-0.086553.fasta
1626-3448-0.089205.fasta
554-2356-0.145751.fasta
663-9278-0.131761.fasta
202-4238-0.169615.fasta
208-6591-0.176254.fasta
900-9352-0.118927.fasta
1859-3090-0.084843.fasta
252-340-0.183732.fasta
2030-5143-0.115054.fasta
164-570-0.170736.fasta
94-2855-0.199494.fasta
468-990-0.148467.fasta
1187-1443-0.140515.fasta
28-3201-0.240991.fasta
1304-5744-0.094229.fasta
838-4735-0.117713.fasta
1218-1812-0.099859.fasta
1435-5104-0.100572.fasta
1583-2203-0.093116.fasta
749-1091-0.134642.fasta
448-3394-0.139610.fasta
1755-4972-0.081716.fasta
56-7723-0.212086.fasta
1062-2354-0.117560.fasta
1822-319-0.075796.fasta
463-1596-0.134555.fasta
604-1410-0.149605.fasta
778-2145-0.125808.fasta
726-4731-0.118448.fasta
254-4470-0.160258.fasta
1504-240-0.091670.fasta
786-2932-0.124891.fasta
319-2472-0.177487.fasta
979-430-0.113077.fasta
1049-8208-0.111373.fasta
505-3176-0.143186.fasta
1178-8796-0.110522.fasta
1135-5739-0.104982.fasta
1308-7106-0.102226.fasta
176-9548-0.171243.fasta
129-9273-0.190098.fasta
537-8099-0.135958.fasta
53-9620-0.209780.fasta
634-2216-0.143387.fasta
72-1406-0.219398.fasta
680-5029-0.121259.fasta
1614-8893-0.091330.fasta
1526-123-0.096773.fasta
1890-241-0.084194.fasta
687-1150-0.121593.fasta
1565-2261-0.087986.fasta
628-8097-0.121129.fasta
109-4380-0.200548.fasta
1090-3570-0.112577.fasta
676-6634-0.138976.fasta
1719-554-0.083996.fasta
169-1727-0.187163.fasta
2065-4633-0.068197.fasta
1073-3777-0.121039.fasta
312-6814-0.174227.fasta
1468-394-0.086638.fasta
86-9356-0.186004.fasta
1413-80-0.121555.fasta
1128-4551-0.105291.fasta
314-7765-0.149513.fasta
867-5973-0.128262.fasta
1991-5165-0.086513.fasta
1121-1649-0.103801.fasta
1763-1101-0.092203.fasta
557-718-0.146418.fasta
46-764-0.226142.fasta
1245-2556-0.109515.fasta
375-8578-0.157388.fasta
944-6220-0.113651.fasta
1466-8215-0.110049.fasta
275-9559-0.174972.fasta
345-49-0.153309.fasta
290-3469-0.153326.fasta
96-3723-0.184796.fasta
1521-72-0.098443.fasta
908-587-0.121781.fasta
1226-2624-0.107281.fasta
183-4105-0.174581.fasta
571-5166-0.132729.fasta
338-7649-0.151037.fasta
1593-1414-0.091119.fasta
975-4133-0.123311.fasta
1252-1935-0.122450.fasta
1238-6229-0.113420.fasta
1280-3558-0.108520.fasta
487-7067-0.137145.fasta
1380-3674-0.112141.fasta
180-1648-0.167749.fasta
373-2308-0.154348.fasta
612-9405-0.136684.fasta
89-9100-0.189183.fasta
162-9742-0.179283.fasta
1690-6347-0.082253.fasta
801-2967-0.115346.fasta
1003-1279-0.116832.fasta
232-497-0.189854.fasta
891-467-0.132008.fasta
307-1619-0.158478.fasta
615-4521-0.135056.fasta
331-581-0.147482.fasta
1449-790-0.093140.fasta
831-8428-0.148615.fasta
928-5581-0.113517.fasta
157-3040-0.173201.fasta
1424-2940-0.088586.fasta
1300-1264-0.091930.fasta
114-8685-0.191462.fasta
851-318-0.127022.fasta
12-9955-0.252646.fasta
1512-6150-0.110121.fasta
1773-3745-0.140783.fasta
103-7787-0.207010.fasta
25-6537-0.227496.fasta
333-7357-0.153714.fasta
123-7152-0.182474.fasta
519-3427-0.154623.fasta
1259-2239-0.113884.fasta
781-3218-0.128665.fasta
1397-793-0.103471.fasta
408-3719-0.153856.fasta
1702-2107-0.088731.fasta
626-952-0.128458.fasta
1196-569-0.109762.fasta
1140-579-0.104124.fasta
8-1685-0.245467.fasta
981-4867-0.111129.fasta
1539-867-0.097263.fasta
403-3021-0.147967.fasta
269-4651-0.157289.fasta
1310-528-0.101914.fasta
846-483-0.117237.fasta
1213-8538-0.116681.fasta
133-9455-0.182645.fasta
1027-5050-0.136504.fasta
1240-2660-0.104449.fasta
1561-6239-0.090921.fasta
357-4497-0.149777.fasta
446-9369-0.138305.fasta
875-4751-0.134985.fasta
1444-1508-0.090271.fasta
1563-157-0.103706.fasta
1011-3429-0.117502.fasta
229-7387-0.162579.fasta
335-3063-0.188735.fasta
532-6438-0.129312.fasta
1161-7303-0.101514.fasta
1144-5960-0.114009.fasta
1433-5796-0.098966.fasta
371-2086-0.145488.fasta
933-2751-0.118706.fasta
1265-7046-0.118915.fasta
390-5548-0.150688.fasta
186-6008-0.171893.fasta
517-6048-0.139684.fasta
118-813-0.179278.fasta
1854-720-0.089883.fasta
641-737-0.136024.fasta
525-1307-0.141324.fasta
1411-4639-0.110231.fasta
1470-7104-0.109600.fasta
718-1764-0.126225.fasta
66-4381-0.208403.fasta
1228-8794-0.122785.fasta
1255-7082-0.106031.fasta
1757-1675-0.078395.fasta
1383-301-0.120632.fasta
2038-10-0.078370.fasta
1082-674-0.108537.fasta
1427-5102-0.103391.fasta
310-567-0.150005.fasta
720-3925-0.132045.fasta
560-5948-0.135073.fasta
736-419-0.131308.fasta
1202-4975-0.097154.fasta
1683-2814-0.091002.fasta
617-723-0.129367.fasta
1700-3165-0.085624.fasta
39-9252-0.218839.fasta
361-7877-0.176812.fasta
1420-2368-0.096223.fasta
37-5563-0.234919.fasta
197-3738-0.162092.fasta
1862-162-0.081004.fasta
1531-633-0.108000.fasta
580-2398-0.132744.fasta
1586-9894-0.091767.fasta
620-1028-0.132514.fasta
646-1287-0.126452.fasta
926-1547-0.125724.fasta
495-1456-0.154614.fasta
44-8165-0.244689.fasta
661-8861-0.136214.fasta
1797-215-0.082853.fasta
493-2731-0.143231.fasta
849-7006-0.113334.fasta
485-172-0.136582.fasta
1578-5663-0.086951.fasta
1194-6092-0.110096.fasta
1022-7910-0.124952.fasta
418-1069-0.143394.fasta
823-603-0.117459.fasta
840-769-0.112757.fasta
1696-5754-0.089175.fasta
999-3536-0.117381.fasta
1207-2443-0.103852.fasta
1640-3478-0.095560.fasta
1487-239-0.103639.fasta
258-266-0.154249.fasta
235-4294-0.162362.fasta
946-39-0.109462.fasta
455-4992-0.145565.fasta
1638-5805-0.087186.fasta
804-8758-0.117930.fasta
412-1783-0.143742.fasta
2072-3-0.066634.fasta
483-1336-0.142266.fasta
1099-9605-0.108772.fasta
439-342-0.159080.fasta
1025-4339-0.125081.fasta
106-2700-0.190300.fasta
567-539-0.139854.fasta
941-565-0.109830.fasta
1545-444-0.111446.fasta
674-4893-0.129073.fasta
1167-962-0.110990.fasta
145-4043-0.177413.fasta
1623-3824-0.099101.fasta
303-292-0.166174.fasta
707-7325-0.120203.fasta
587-9174-0.144834.fasta
758-1209-0.126513.fasta
2028-781-0.070886.fasta
860-3270-0.131817.fasta
608-7050-0.133622.fasta
810-2678-0.113335.fasta
919-3338-0.117785.fasta
1674-231-0.095453.fasta
1155-2475-0.109870.fasta
938-109-0.120151.fasta
154-4890-0.173415.fasta
2121-4459-0.064140.fasta
1844-169-0.072437.fasta
1483-2200-0.132799.fasta
767-5857-0.128956.fasta
265-8349-0.161768.fasta
248-6854-0.168706.fasta
589-8726-0.143757.fasta
843-8466-0.126061.fasta
1224-7823-0.108075.fasta
1431-9885-0.092113.fasta
1287-6653-0.095228.fasta
1852-2110-0.149486.fasta
1110-2464-0.113581.fasta
1088-463-0.123335.fasta
427-5889-0.140839.fasta
1884-1111-0.102719.fasta
111-664-0.184610.fasta
1537-6216-0.092969.fasta
833-766-0.141370.fasta
1782-8775-0.110743.fasta
0-6474-0.280390.fasta
359-624-0.153360.fasta
460-3567-0.144011.fasta
1894-932-0.072337.fasta
205-4955-0.161523.fasta
1386-7913-0.098710.fasta
1209-3484-0.106632.fasta
600-2998-0.134211.fasta
141-7287-0.176708.fasta
2185-516-0.035892.fasta
1463-6825-0.109307.fasta
1997-249-0.074381.fasta
1933-3238-0.067444.fasta
1317-2100-0.093073.fasta
273-748-0.159638.fasta
284-5114-0.162272.fasta
1232-3172-0.106561.fasta
349-7561-0.143661.fasta
385-5881-0.141656.fasta
789-7810-0.125102.fasta
569-7114-0.147178.fasta
2033-6484-0.087639.fasta
2179-5940-0.041073.fasta
990-622-0.111062.fasta
705-6741-0.122437.fasta
457-6340-0.148863.fasta
794-4117-0.131743.fasta
1874-2972-0.071183.fasta
1284-3453-0.102658.fasta
281-125-0.156444.fasta
241-9558-0.182145.fasta
305-7638-0.153371.fasta
545-9930-0.141450.fasta
1348-9155-0.107162.fasta
762-976-0.124246.fasta
1198-3162-0.108545.fasta
522-9151-0.130083.fasta
2195-356-0.032152.fasta
383-2918-0.161629.fasta
2242-2926-0.034278.fasta
654-9147-0.147749.fasta
159-7391-0.183015.fasta
416-411-0.147560.fasta
576-9362-0.137495.fasta
1148-681-0.109306.fasta
1040-970-0.114051.fasta
1667-4343-0.097883.fasta
271-1141-0.156378.fasta
1841-1524-0.073214.fasta
131-667-0.185933.fasta
296-5192-0.166399.fasta
565-5197-0.131444.fasta
316-135-0.158834.fasta
887-7500-0.134104.fasta
2091-4769-0.058793.fasta
394-1017-0.151824.fasta
239-9274-0.179305.fasta
1994-8232-0.070494.fasta
2010-2486-0.064716.fasta
1595-2319-0.095968.fasta
2159-2095-0.049811.fasta
298-152-0.157300.fasta
1571-1278-0.087412.fasta
2191-367-0.040062.fasta
2201-6293-0.056341.fasta
515-2997-0.131760.fasta
1163-4877-0.124322.fasta
648-950-0.127158.fasta
1047-5941-0.111042.fasta
1101-384-0.119098.fasta
244-1213-0.202077.fasta
471-8859-0.139899.fasta
770-6381-0.129148.fasta
1390-1182-0.113314.fasta
422-4144-0.168074.fasta
1314-7158-0.113732.fasta
490-2821-0.133295.fasta
1929-51-0.076950.fasta
1272-5776-0.102128.fasta
173-1552-0.178052.fasta
878-1325-0.129263.fasta
420-7645-0.144285.fasta
1670-87-0.085233.fasta
527-770-0.141802.fasta
68-1671-0.212316.fasta
21-1241-0.235038.fasta
1157-472-0.101546.fasta
1476-4157-0.109577.fasta
1395-5727-0.134538.fasta
930-2865-0.107954.fasta
433-4969-0.137484.fasta
41-471-0.218785.fasta
1370-7402-0.127165.fasta
2189-5218-0.051769.fasta
828-1533-0.117079.fasta
682-6076-0.124199.fasta
188-9608-0.166862.fasta
263-2060-0.167351.fasta
755-6609-0.123060.fasta
10-3523-0.246199.fasta
1277-707-0.137718.fasta
1037-2326-0.116073.fasta
425-8066-0.168329.fasta
1079-4487-0.143224.fasta
322-398-0.150702.fasta
1126-3703-0.102240.fasta
396-4097-0.160117.fasta
406-8869-0.149918.fasta
1818-551-0.108973.fasta
1330-8836-0.098664.fasta
481-9050-0.153455.fasta
1005-6-0.111093.fasta
690-2550-0.135574.fasta
261-5467-0.168674.fasta
1103-424-0.106836.fasta
1569-1709-0.088260.fasta
2068-5994-0.076659.fasta
59-4927-0.230506.fasta
84-3693-0.187239.fasta
166-5463-0.176153.fasta
1813-9087-0.078854.fasta
1876-1743-0.079137.fasta
224-1686-0.165532.fasta
1216-2059-0.103901.fasta
2070-1436-0.066415.fasta
652-9390-0.138155.fasta
1902-50-0.076828.fasta
34-4575-0.228624.fasta
503-7251-0.149779.fasta
1492-1715-0.086203.fasta
2079-2937-0.068457.fasta
501-9944-0.146231.fasta
23-4848-0.240759.fasta
1497-1693-0.096950.fasta
1060-6811-0.134804.fasta
1108-6787-0.124635.fasta
987-4210-0.123844.fasta
78-6271-0.191502.fasta
1404-1070-0.101660.fasta
1367-8497-0.103366.fasta
431-7285-0.165084.fasta
14-7213-0.246389.fasta
656-656-0.127469.fasta
1001-2890-0.153484.fasta
821-1798-0.120401.fasta
221-6956-0.169978.fasta
195-4138-0.173305.fasta
595-7771-0.128292.fasta
18-1917-0.235976.fasta
1447-6197-0.110214.fasta
1786-8720-0.088003.fasta
1848-5370-0.093392.fasta
120-2163-0.188661.fasta
1554-560-0.084050.fasta
630-6233-0.135832.fasta
906-8826-0.114949.fasta
1567-1447-0.108882.fasta
1096-5577-0.103127.fasta
388-5876-0.141592.fasta
61-1983-0.214267.fasta
1045-8560-0.106177.fasta
1422-2740-0.106355.fasta
340-3720-0.161451.fasta
2129-9197-0.054639.fasta
914-9575-0.113131.fasta
1016-6043-0.110506.fasta
479-7131-0.136949.fasta
700-3370-0.137698.fasta
1455-3908-0.091470.fasta
712-465-0.135495.fasta
606-3471-0.138199.fasta
1439-5457-0.096170.fasta
1191-722-0.136671.fasta
101-3827-0.199580.fasta
378-8175-0.152357.fasta
1712-875-0.083860.fasta
1184-5982-0.101862.fasta
80-7240-0.201192.fasta
1393-466-0.090283.fasta
624-6077-0.163222.fasta
1685-261-0.092839.fasta
917-2064-0.142043.fasta
139-1353-0.196898.fasta
1274-866-0.101757.fasta
1936-6226-0.086864.fasta
135-3432-0.177679.fasta
392-6091-0.174867.fasta
825-5586-0.154026.fasta
1726-504-0.094491.fasta
148-4553-0.182308.fasta
1282-6182-0.101279.fasta
693-280-0.128498.fasta
508-3765-0.155645.fasta
1106-1058-0.126441.fasta
1729-1351-0.103116.fasta
31-2705-0.228264.fasta
442-8545-0.157898.fasta
435-5865-0.157011.fasta
1018-1257-0.109866.fasta
542-1180-0.138881.fasta
1114-453-0.116355.fasta
949-4352-0.117339.fasta
1119-3692-0.116288.fasta
1807-5159-0.098979.fasta
444-2362-0.144459.fasta
116-6341-0.193832.fasta
818-97-0.118878.fasta
1057-2050-0.121383.fasta
1042-1859-0.123967.fasta
1067-6768-0.116656.fasta
1071-314-0.126420.fasta
1373-6524-0.105837.fasta
1131-547-0.114475.fasta
1292-1376-0.096727.fasta
1344-95-0.127878.fasta
76-3619-0.203433.fasta
808-1117-0.142394.fasta
292-4009-0.169455.fasta
327-5461-0.153394.fasta
63-883-0.214841.fasta
889-3900-0.109850.fasta
697-989-0.152141.fasta
983-4878-0.119594.fasta
729-3573-0.123309.fasta
636-939-0.129816.fasta
1094-1608-0.109349.fasta
92-9003-0.208488.fasta
1722-3596-0.094760.fasta
1092-6099-0.121512.fasta
574-6118-0.150862.fasta
2153-4819-0.044058.fasta
1999-33-0.100968.fasta
497-8599-0.155492.fasta
2233-3562-0.040695.fasta
2096-3406-0.054791.fasta
1857-111-0.094438.fasta
791-9591-0.150075.fasta
381-5413-0.165635.fasta
703-110-0.129666.fasta
865-2070-0.124918.fasta
1909-8911-0.082987.fasta
125-8986-0.205144.fasta
650-4573-0.123718.fasta
895-7475-0.129919.fasta
351-840-0.155096.fasta
638-2612-0.143059.fasta
1616-1813-0.088562.fasta
2-431-0.267960.fasta
1182-6266-0.107268.fasta
5-8929-0.252810.fasta
1032-9555-0.125431.fasta
1529-9021-0.089494.fasta
2250-1-0.009371.fasta
2177-688-0.093981.fasta

                       sample  df1_total  df2_total  shared_snps
0     659-7827-0.129215.fasta        8.0        7.0            6
1       199-99-0.164007.fasta        5.0        5.0            5
2     286-3036-0.159561.fasta        7.0        7.0            6
3    1174-9602-0.106911.fasta        5.0        5.0            5
4     765-6965-0.125270.fasta        7.0        7.0            7
..                        ...        ...        ...          ...
547     5-8929-0.252810.fasta       13.0       13.0           13
548  1032-9555-0.125431.fasta        8.0        8.0            8
549  1529-9021-0.089494.fasta        4.0        4.0            4
550     2250-1-0.009371.fasta        2.0        2.0            2
551   2177-688-0.093981.fasta        3.0        3.0            3

[552 rows x 4 columns]

In [28]:
int(overlap_df['df1_total'].sum()), overlap_df['df2_total'].sum(), overlap_df['shared_snps'].sum()

(3655, np.float64(3647.0), np.int64(3621))